# Generated by Django 4.2.6 on 2024-02-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nutrition_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaloriesNeeded', models.IntegerField(default=2000)),
                ('SaturatedFatContent', models.IntegerField(default=25)),
                ('CholesterolContent', models.IntegerField(default=130)),
                ('SodiumContent', models.IntegerField(default=50)),
                ('CarbohydrateContent', models.IntegerField(default=250)),
                ('FiberContent', models.IntegerField(default=20)),
                ('SugarContent', models.IntegerField(default=100)),
                ('ProteinContent', models.IntegerField(default=50)),
                ('num_recomm', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='person_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
                ('height', models.IntegerField(default=150)),
                ('weight', models.IntegerField(default=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('activity', models.CharField(max_length=50)),
                ('weight_plan', models.CharField(max_length=50)),
                ('meals', models.IntegerField(default=3)),
            ],
        ),
    ]
