# Generated by Django 4.2.6 on 2024-02-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition_details',
            name='CarbohydrateContent',
        ),
        migrations.RemoveField(
            model_name='nutrition_details',
            name='CholesterolContent',
        ),
        migrations.RemoveField(
            model_name='nutrition_details',
            name='FiberContent',
        ),
        migrations.RemoveField(
            model_name='nutrition_details',
            name='ProteinContent',
        ),
        migrations.RemoveField(
            model_name='nutrition_details',
            name='SaturatedFatContent',
        ),
        migrations.RemoveField(
            model_name='nutrition_details',
            name='SodiumContent',
        ),
        migrations.RemoveField(
            model_name='nutrition_details',
            name='SugarContent',
        ),
        migrations.RemoveField(
            model_name='nutrition_details',
            name='num_recomm',
        ),
        migrations.AlterField(
            model_name='nutrition_details',
            name='CaloriesNeeded',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person_details',
            name='activity',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('extra_active', 'Extra Active')], default='sedentary', max_length=50),
        ),
        migrations.AlterField(
            model_name='person_details',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50),
        ),
        migrations.AlterField(
            model_name='person_details',
            name='meals',
            field=models.IntegerField(choices=[(3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AlterField(
            model_name='person_details',
            name='weight_plan',
            field=models.CharField(choices=[('maintain_weight', 'Maintain Weight'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain')], default='maintain_weight', max_length=50),
        ),
    ]
