# Generated by Django 4.2.6 on 2024-02-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_nutrition_details_carbohydratecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition_details',
            name='CarbohydrateContent',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='nutrition_details',
            name='CholesterolContent',
            field=models.IntegerField(default=130),
        ),
        migrations.AddField(
            model_name='nutrition_details',
            name='FiberContent',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='nutrition_details',
            name='ProteinContent',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='nutrition_details',
            name='SaturatedFatContent',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='nutrition_details',
            name='SodiumContent',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='nutrition_details',
            name='SugarContent',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='nutrition_details',
            name='num_recomm',
            field=models.IntegerField(default=5),
        ),
    ]
