# Generated by Django 4.2.6 on 2024-02-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_nutrition_details_carbohydratecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='namaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='person_details',
            name='height',
            field=models.FloatField(default=150.0),
        ),
        migrations.AlterField(
            model_name='person_details',
            name='weight',
            field=models.FloatField(default=50.0),
        ),
    ]
